### PR TITLE
Add reagents costs to spell page

### LINKED ISSUE #2: Feature Request: Lookup craft cost for craft spells
Is it possible to add a lookup for the craft cost on crafting spells?

e.g. https://tbc.wowhead.com/spell=31432/runic-spellthread could show craft cost (and even profit 🙏🏽 ) while https://tbc.wowhead.com/item=24274/runic-spellthread would show the market value?

### PR DESCRIPTION
**Pull request by sandervspl**
This feature will add a new tooltip to the crafting spell page with the estimated cost of crafting the item, with each item showing their total cost (based on the cheapest buyout price for that item on your server).

### CODE REVIEW

**Comment by sandervspl** [comment]
Screenshot 2022-06-24 at 18 03 55

The current implementation.

**Comment by tstirrat** [comment]
Looks great! If possible it would be great to see the profit, too.

Love it already though!

**Comment by sandervspl** [comment]
Good idea. Will see what I can do!

**Comment by sandervspl** [comment]
Closing (finally) this pull request in favor of #7

**Pull request closed without merging**
